format = """
[ \uf120 ](bg:#3e3e42 fg:#1e1e1e)\
[](bg:#007acc fg:#3e3e42)\
$directory\
[](fg:#007acc bg:#2d2d30)\
$git_branch\
$git_status\
[](fg:#2d2d30 bg:#252526)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#252526 bg:#1e1e1e)\
$time\
[ ](fg:#1e1e1e)\
\n$character"""

[directory]
style = "fg:#d4d4d4 bg:#007acc"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#2d2d30"
format = '[[ $symbol $branch ](fg:#b5cea8 bg:#2d2d30)]($style)'

[git_status]
style = "bg:#2d2d30"
format = '[[($all_status$ahead_behind )](fg:#b5cea8 bg:#2d2d30)]($style)'

[nodejs]
symbol = ""
style = "bg:#252526"
format = '[[ $symbol ($version) ](fg:#4ec9b0 bg:#252526)]($style)'

[rust]
symbol = ""
style = "bg:#252526"
format = '[[ $symbol ($version) ](fg:#c586c0 bg:#252526)]($style)'

[golang]
symbol = ""
style = "bg:#252526"
format = '[[ $symbol ($version) ](fg:#4ec9b0 bg:#252526)]($style)'

[php]
symbol = ""
style = "bg:#252526"
format = '[[ $symbol ($version) ](fg:#ce9178 bg:#252526)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#1e1e1e"
format = '[[  $time ](fg:#d4d4d4 bg:#1e1e1e)]($style)'
