#!/usr/bin/env bash
read -r _ u1 n1 s1 i1 w1 r1 q1 < /proc/stat
sleep 0.5
read -r _ u2 n2 s2 i2 w2 r2 q2 < /proc/stat
t1=$((u1+n1+s1+i1+w1+r1+q1))
t2=$((u2+n2+s2+i2+w2+r2+q2))
printf "%.0f\n" $(echo "scale=2; (1 - ($i2+$w2-$i1-$w1)/($t2-$t1)) * 100" | bc)
