#!/usr/bin/env bash

strength=`iwconfig 2>/dev/null | grep "Link Quality=" | awk -F'=' '{ print $2 }' | awk -F'/' '{ print $1 }'`
state=`iwconfig 2>/dev/null | grep ESSID | awk -F':' '{ print $2 }' | xargs`
wf=`echo "${strength:-0}*100/70" | bc 2>/dev/null || echo 0`

icon() {
  if [[ $wf -eq 0 ]]; then
    echo "images/wifi-off.svg"
  elif [[ $wf -le 30 ]]; then
    echo "images/wifi-low.svg"
  elif [[ $wf -le 60 ]]; then
    echo "images/wifi-medium.svg"
  elif [[ $wf -gt 60 ]]; then
    echo "images/wifi-high.svg"
  else
    echo "images/wifi-off.svg"
  fi
}

percentage() {
  if [[ $wf -ge 0 ]]; then
    echo "$wf%"
  else
    echo "Disconnected"
  fi
}

if [[ $1 == icon ]]; then
  icon
elif [[ $1 == percentage ]]; then
  percentage
fi
