#!/usr/bin/env bash

python3 scripts/workspaces.py
socat -U - UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r _ ; do
  python3 scripts/workspaces.py
done
