format = """
╭$directory\
$git_branch\
$git_status\
$nodejs\
$rust\
$golang\
$php\
$time\
\n╰$character"""

palette = "pywal"

[palettes.pywal]
background = "{background}"
foreground = "{foreground}"
color0 = "{color0}"
color1 = "{color1}"
color2 = "{color2}"
color3 = "{color3}"
color4 = "{color4}"
color5 = "{color5}"
color6 = "{color6}"
color7 = "{color7}"
color8 = "{color8}"
color9 = "{color9}"

[character]
success_symbol = "[](fg:color4)"
error_symbol = "[](fg:color1)"

[directory]
style = "fg:color7"
format = '[  $path ]($style)'
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "fg:color5"
format = '[\[$symbol $branch\]]($style)'

[git_status]
style = "fg:color5"
format = '([\[$all_status$ahead_behind\]]($style))'

[nodejs]
symbol = ""
style = "fg:color3"
format = '[\[$symbol ($version)\]]($style)'

[rust]
symbol = ""
style = "fg:color6"
format = '[\[$symbol ($version)\]]($style)'

[golang]
symbol = ""
style = "fg:color4"
format = '[\[$symbol ($version)\]]($style)'

[php]
symbol = ""
style = "fg:color5"
format = '[\[$symbol ($version)\]]($style)'

[time]
disabled = false
time_format = "%R"
style = "fg:foreground"
format = '[\[󰥔 $time\]]($style)'
