# Hyprpaper configuration

# Preload wallpapers
preload = ~/.config/walls/wall1.png
preload = ~/.config/walls/illust_116086929_20240229_230750.jpg
preload = ~/.config/walls/illust_116916742_20240328_013832.jpg
preload = ~/.config/walls/illust_132610892_20250713_000953.png
preload = ~/.config/walls/large_asf_goodbg.png
preload = ~/.config/walls/lock.jpg

# Set default wallpaper (empty monitor name = all monitors)
wallpaper = ,~/.config/walls/lock.jpg
# Disable splash
splash = false

ipc = on
